name: Build and Deploy React App

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_PUBLIC_URL: 'https://jwhunt19.github.io/spotify-csv-exporter/'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
